// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.example.proto;

@SuppressWarnings({ "rawtypes", "unused" })
public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface Spec_QTwHw2YxY9EFXmPrzmX4pXOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX}
   *
   * <pre>
   * Google Protocol Buffer for 'Raspberrry Pi Default'.
   * Generated on 2014.03.02 00:52:18 UTC
   * </pre>
   */
  public static final class Spec_QTwHw2YxY9EFXmPrzmX4pX extends
      com.google.protobuf.GeneratedMessageLite
      implements Spec_QTwHw2YxY9EFXmPrzmX4pXOrBuilder {
    // Use Spec_QTwHw2YxY9EFXmPrzmX4pX.newBuilder() to construct.
    private Spec_QTwHw2YxY9EFXmPrzmX4pX(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Spec_QTwHw2YxY9EFXmPrzmX4pX(boolean noInit) {}

    private static final Spec_QTwHw2YxY9EFXmPrzmX4pX defaultInstance;
    public static Spec_QTwHw2YxY9EFXmPrzmX4pX getDefaultInstance() {
      return defaultInstance;
    }

    public Spec_QTwHw2YxY9EFXmPrzmX4pX getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Spec_QTwHw2YxY9EFXmPrzmX4pX(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Spec_QTwHw2YxY9EFXmPrzmX4pX> PARSER =
        new com.google.protobuf.AbstractParser<Spec_QTwHw2YxY9EFXmPrzmX4pX>() {
      public Spec_QTwHw2YxY9EFXmPrzmX4pX parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Spec_QTwHw2YxY9EFXmPrzmX4pX(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Spec_QTwHw2YxY9EFXmPrzmX4pX> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.Command}
     */
    public enum Command
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>PING = 1;</code>
       */
      PING(0, 1),
      /**
       * <code>TESTEVENTS = 2;</code>
       */
      TESTEVENTS(1, 2),
      /**
       * <code>HELLOWORLD = 3;</code>
       */
      HELLOWORLD(2, 3),
      ;

      /**
       * <code>PING = 1;</code>
       */
      public static final int PING_VALUE = 1;
      /**
       * <code>TESTEVENTS = 2;</code>
       */
      public static final int TESTEVENTS_VALUE = 2;
      /**
       * <code>HELLOWORLD = 3;</code>
       */
      public static final int HELLOWORLD_VALUE = 3;


      public final int getNumber() { return value; }

      public static Command valueOf(int value) {
        switch (value) {
          case 1: return PING;
          case 2: return TESTEVENTS;
          case 3: return HELLOWORLD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };

      private final int value;

      private Command(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.Command)
    }

    public interface _HeaderOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;
      /**
       * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
       */
      boolean hasCommand();
      /**
       * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
       */
      com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command getCommand();

      // optional string originator = 2;
      /**
       * <code>optional string originator = 2;</code>
       */
      boolean hasOriginator();
      /**
       * <code>optional string originator = 2;</code>
       */
      java.lang.String getOriginator();
      /**
       * <code>optional string originator = 2;</code>
       */
      com.google.protobuf.ByteString
          getOriginatorBytes();
    }
    /**
     * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX._Header}
     */
    public static final class _Header extends
        com.google.protobuf.GeneratedMessageLite
        implements _HeaderOrBuilder {
      // Use _Header.newBuilder() to construct.
      private _Header(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private _Header(boolean noInit) {}

      private static final _Header defaultInstance;
      public static _Header getDefaultInstance() {
        return defaultInstance;
      }

      public _Header getDefaultInstanceForType() {
        return defaultInstance;
      }

      private _Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command value = com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000001;
                  command_ = value;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                originator_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<_Header> PARSER =
          new com.google.protobuf.AbstractParser<_Header>() {
        public _Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new _Header(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<_Header> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;
      public static final int COMMAND_FIELD_NUMBER = 1;
      private com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command_;
      /**
       * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
       */
      public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command getCommand() {
        return command_;
      }

      // optional string originator = 2;
      public static final int ORIGINATOR_FIELD_NUMBER = 2;
      private java.lang.Object originator_;
      /**
       * <code>optional string originator = 2;</code>
       */
      public boolean hasOriginator() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string originator = 2;</code>
       */
      public java.lang.String getOriginator() {
        java.lang.Object ref = originator_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            originator_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string originator = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOriginatorBytes() {
        java.lang.Object ref = originator_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        command_ = com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command.PING;
        originator_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasCommand()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, command_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getOriginatorBytes());
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, command_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getOriginatorBytes());
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX._Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header, Builder>
          implements com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._HeaderOrBuilder {
        // Construct using com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          command_ = com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command.PING;
          bitField0_ = (bitField0_ & ~0x00000001);
          originator_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header getDefaultInstanceForType() {
          return com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header.getDefaultInstance();
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header build() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header buildPartial() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header result = new com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.command_ = command_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.originator_ = originator_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header other) {
          if (other == com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header.getDefaultInstance()) return this;
          if (other.hasCommand()) {
            setCommand(other.getCommand());
          }
          if (other.hasOriginator()) {
            bitField0_ |= 0x00000002;
            originator_ = other.originator_;
            
          }
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCommand()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;
        private com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command_ = com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command.PING;
        /**
         * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
         */
        public boolean hasCommand() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
         */
        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command getCommand() {
          return command_;
        }
        /**
         * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
         */
        public Builder setCommand(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          command_ = value;
          
          return this;
        }
        /**
         * <code>required .Spec_QTwHw2YxY9EFXmPrzmX4pX.Command command = 1;</code>
         */
        public Builder clearCommand() {
          bitField0_ = (bitField0_ & ~0x00000001);
          command_ = com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.Command.PING;
          
          return this;
        }

        // optional string originator = 2;
        private java.lang.Object originator_ = "";
        /**
         * <code>optional string originator = 2;</code>
         */
        public boolean hasOriginator() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string originator = 2;</code>
         */
        public java.lang.String getOriginator() {
          java.lang.Object ref = originator_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            originator_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string originator = 2;</code>
         */
        public com.google.protobuf.ByteString
            getOriginatorBytes() {
          java.lang.Object ref = originator_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            originator_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string originator = 2;</code>
         */
        public Builder setOriginator(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          originator_ = value;
          
          return this;
        }
        /**
         * <code>optional string originator = 2;</code>
         */
        public Builder clearOriginator() {
          bitField0_ = (bitField0_ & ~0x00000002);
          originator_ = getDefaultInstance().getOriginator();
          
          return this;
        }
        /**
         * <code>optional string originator = 2;</code>
         */
        public Builder setOriginatorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          originator_ = value;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX._Header)
      }

      static {
        defaultInstance = new _Header(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX._Header)
    }

    public interface pingOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
    }
    /**
     * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.ping}
     */
    public static final class ping extends
        com.google.protobuf.GeneratedMessageLite
        implements pingOrBuilder {
      // Use ping.newBuilder() to construct.
      private ping(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private ping(boolean noInit) {}

      private static final ping defaultInstance;
      public static ping getDefaultInstance() {
        return defaultInstance;
      }

      public ping getDefaultInstanceForType() {
        return defaultInstance;
      }

      private ping(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<ping> PARSER =
          new com.google.protobuf.AbstractParser<ping>() {
        public ping parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ping(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ping> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.ping}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping, Builder>
          implements com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.pingOrBuilder {
        // Construct using com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping getDefaultInstanceForType() {
          return com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping.getDefaultInstance();
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping build() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping buildPartial() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping result = new com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping(this);
          return result;
        }

        public Builder mergeFrom(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping other) {
          if (other == com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping.getDefaultInstance()) return this;
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.ping) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.ping)
      }

      static {
        defaultInstance = new ping(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.ping)
    }

    public interface testEventsOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
    }
    /**
     * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents}
     */
    public static final class testEvents extends
        com.google.protobuf.GeneratedMessageLite
        implements testEventsOrBuilder {
      // Use testEvents.newBuilder() to construct.
      private testEvents(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private testEvents(boolean noInit) {}

      private static final testEvents defaultInstance;
      public static testEvents getDefaultInstance() {
        return defaultInstance;
      }

      public testEvents getDefaultInstanceForType() {
        return defaultInstance;
      }

      private testEvents(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<testEvents> PARSER =
          new com.google.protobuf.AbstractParser<testEvents>() {
        public testEvents parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new testEvents(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<testEvents> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents, Builder>
          implements com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEventsOrBuilder {
        // Construct using com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents getDefaultInstanceForType() {
          return com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents.getDefaultInstance();
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents build() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents buildPartial() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents result = new com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents(this);
          return result;
        }

        public Builder mergeFrom(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents other) {
          if (other == com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents.getDefaultInstance()) return this;
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents)
      }

      static {
        defaultInstance = new testEvents(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.testEvents)
    }

    public interface helloWorldOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // required string greeting = 1;
      /**
       * <code>required string greeting = 1;</code>
       */
      boolean hasGreeting();
      /**
       * <code>required string greeting = 1;</code>
       */
      java.lang.String getGreeting();
      /**
       * <code>required string greeting = 1;</code>
       */
      com.google.protobuf.ByteString
          getGreetingBytes();

      // required bool loud = 2;
      /**
       * <code>required bool loud = 2;</code>
       */
      boolean hasLoud();
      /**
       * <code>required bool loud = 2;</code>
       */
      boolean getLoud();
    }
    /**
     * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld}
     */
    public static final class helloWorld extends
        com.google.protobuf.GeneratedMessageLite
        implements helloWorldOrBuilder {
      // Use helloWorld.newBuilder() to construct.
      private helloWorld(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private helloWorld(boolean noInit) {}

      private static final helloWorld defaultInstance;
      public static helloWorld getDefaultInstance() {
        return defaultInstance;
      }

      public helloWorld getDefaultInstanceForType() {
        return defaultInstance;
      }

      private helloWorld(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                greeting_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                loud_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<helloWorld> PARSER =
          new com.google.protobuf.AbstractParser<helloWorld>() {
        public helloWorld parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new helloWorld(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<helloWorld> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string greeting = 1;
      public static final int GREETING_FIELD_NUMBER = 1;
      private java.lang.Object greeting_;
      /**
       * <code>required string greeting = 1;</code>
       */
      public boolean hasGreeting() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string greeting = 1;</code>
       */
      public java.lang.String getGreeting() {
        java.lang.Object ref = greeting_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            greeting_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string greeting = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGreetingBytes() {
        java.lang.Object ref = greeting_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          greeting_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required bool loud = 2;
      public static final int LOUD_FIELD_NUMBER = 2;
      private boolean loud_;
      /**
       * <code>required bool loud = 2;</code>
       */
      public boolean hasLoud() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool loud = 2;</code>
       */
      public boolean getLoud() {
        return loud_;
      }

      private void initFields() {
        greeting_ = "";
        loud_ = false;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasGreeting()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLoud()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getGreetingBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBool(2, loud_);
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getGreetingBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, loud_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld, Builder>
          implements com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorldOrBuilder {
        // Construct using com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          greeting_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          loud_ = false;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld getDefaultInstanceForType() {
          return com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld.getDefaultInstance();
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld build() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld buildPartial() {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld result = new com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.greeting_ = greeting_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.loud_ = loud_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld other) {
          if (other == com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld.getDefaultInstance()) return this;
          if (other.hasGreeting()) {
            bitField0_ |= 0x00000001;
            greeting_ = other.greeting_;
            
          }
          if (other.hasLoud()) {
            setLoud(other.getLoud());
          }
          return this;
        }

        public final boolean isInitialized() {
          if (!hasGreeting()) {
            
            return false;
          }
          if (!hasLoud()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string greeting = 1;
        private java.lang.Object greeting_ = "";
        /**
         * <code>required string greeting = 1;</code>
         */
        public boolean hasGreeting() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string greeting = 1;</code>
         */
        public java.lang.String getGreeting() {
          java.lang.Object ref = greeting_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            greeting_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string greeting = 1;</code>
         */
        public com.google.protobuf.ByteString
            getGreetingBytes() {
          java.lang.Object ref = greeting_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            greeting_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string greeting = 1;</code>
         */
        public Builder setGreeting(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          greeting_ = value;
          
          return this;
        }
        /**
         * <code>required string greeting = 1;</code>
         */
        public Builder clearGreeting() {
          bitField0_ = (bitField0_ & ~0x00000001);
          greeting_ = getDefaultInstance().getGreeting();
          
          return this;
        }
        /**
         * <code>required string greeting = 1;</code>
         */
        public Builder setGreetingBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          greeting_ = value;
          
          return this;
        }

        // required bool loud = 2;
        private boolean loud_ ;
        /**
         * <code>required bool loud = 2;</code>
         */
        public boolean hasLoud() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bool loud = 2;</code>
         */
        public boolean getLoud() {
          return loud_;
        }
        /**
         * <code>required bool loud = 2;</code>
         */
        public Builder setLoud(boolean value) {
          bitField0_ |= 0x00000002;
          loud_ = value;
          
          return this;
        }
        /**
         * <code>required bool loud = 2;</code>
         */
        public Builder clearLoud() {
          bitField0_ = (bitField0_ & ~0x00000002);
          loud_ = false;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld)
      }

      static {
        defaultInstance = new helloWorld(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Spec_QTwHw2YxY9EFXmPrzmX4pX}
     *
     * <pre>
     * Google Protocol Buffer for 'Raspberrry Pi Default'.
     * Generated on 2014.03.02 00:52:18 UTC
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX, Builder>
        implements com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pXOrBuilder {
      // Construct using com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX getDefaultInstanceForType() {
        return com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.getDefaultInstance();
      }

      public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX build() {
        com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX buildPartial() {
        com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX result = new com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX(this);
        return result;
      }

      public Builder mergeFrom(com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX other) {
        if (other == com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.getDefaultInstance()) return this;
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX)
    }

    static {
      defaultInstance = new Spec_QTwHw2YxY9EFXmPrzmX4pX(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Spec_QTwHw2YxY9EFXmPrzmX4pX)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
