/*
 * ExampleCommandProcessor.java 
 * --------------------------------------------------------------------------------------
 * Copyright (c) Reveal Technologies, LLC. All rights reserved. http://www.reveal-tech.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package com.example;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Logger;

import com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX._Header;
import com.example.proto.Example.Spec_QTwHw2YxY9EFXmPrzmX4pX.helloWorld;
import com.sitewhere.agent.BaseCommandProcessor;
import com.sitewhere.agent.ISiteWhereEventDispatcher;
import com.sitewhere.agent.SiteWhereAgentException;
import com.sitewhere.device.provisioning.protobuf.proto.Sitewhere.Device.Header;
import com.sitewhere.device.provisioning.protobuf.proto.Sitewhere.Device.RegistrationAck;
import com.sitewhere.device.provisioning.protobuf.proto.Sitewhere.SiteWhere;
import com.sitewhere.device.provisioning.protobuf.proto.Sitewhere.SiteWhere.RegisterDevice;

/**
 * Example of command processing from a protobuf descriptor generated by SiteWhere.
 * 
 * @author Derek
 */
public class ExampleCommandProcessor extends BaseCommandProcessor {

	/** Static logger instance */
	private static Logger LOGGER = Logger.getLogger(ExampleCommandProcessor.class.getName());

	/** Hardware id */
	private String hardwareId;

	/** Specification token */
	private String specificationToken;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.sitewhere.agent.BaseCommandProcessor#executeStartupLogic(java.lang.String,
	 * java.lang.String, com.sitewhere.agent.ISiteWhereEventDispatcher)
	 */
	@Override
	public void executeStartupLogic(String hardwareId, String specificationToken,
			ISiteWhereEventDispatcher dispatcher) throws SiteWhereAgentException {
		this.hardwareId = hardwareId;
		this.specificationToken = specificationToken;

		RegisterDevice.Builder builder = RegisterDevice.newBuilder();
		RegisterDevice register =
				builder.setHardwareId(hardwareId).setSpecificationToken(specificationToken).build();
		dispatcher.registerDevice(register, null);
		LOGGER.info("Sent registration information.");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.sitewhere.agent.BaseCommandProcessor#handleRegisterAck(com.sitewhere.device
	 * .provisioning.protobuf.proto.Sitewhere.Device.Header,
	 * com.sitewhere.device.provisioning.protobuf.proto.Sitewhere.Device.RegistrationAck)
	 */
	@Override
	public void handleRegisterAck(Header header, RegistrationAck ack) {
		switch (ack.getState()) {
		case NEW_REGISTRATION: {
			LOGGER.info("SiteWhere indicated device was successfully registered.");
			break;
		}
		case ALREADY_REGISTERED: {
			LOGGER.info("SiteWhere indicated device is using an existing registration.");
			break;
		}
		case REGISTRATION_ERROR: {
			LOGGER.warning("SiteWhere indicated a device registration error.");
			break;
		}
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.sitewhere.agent.BaseCommandProcessor#processSpecificationCommand(byte[],
	 * com.sitewhere.agent.ISiteWhereEventDispatcher)
	 */
	@Override
	public void processSpecificationCommand(byte[] message, ISiteWhereEventDispatcher dispatcher)
			throws SiteWhereAgentException {
		ByteArrayInputStream stream = new ByteArrayInputStream(message);
		try {
			_Header header = _Header.parseDelimitedFrom(stream);
			switch (header.getCommand()) {
			case HELLOWORLD: {
				helloWorld hw = helloWorld.parseDelimitedFrom(stream);
				String response = hw.getGreeting() + " World!";
				if (hw.getLoud()) {
					response = response.toUpperCase();
				}
				SiteWhere.Acknowledge.Builder builder = SiteWhere.Acknowledge.newBuilder();
				SiteWhere.Acknowledge ack =
						builder.setHardwareId(getHardwareId()).setMessage(response).build();
				dispatcher.acknowledge(ack, header.getOriginator());
			}
			case PING: {
			}
			case TESTEVENTS: {
			}
			}
		} catch (IOException e) {
			throw new SiteWhereAgentException(e);
		}
	}

	public String getHardwareId() {
		return hardwareId;
	}

	public void setHardwareId(String hardwareId) {
		this.hardwareId = hardwareId;
	}

	public String getSpecificationToken() {
		return specificationToken;
	}

	public void setSpecificationToken(String specificationToken) {
		this.specificationToken = specificationToken;
	}
}